services:
  web:
    build:
      context: .
      dockerfile: release/prod.Dockerfile
    ports:
      - 80:80
    restart: always
    volumes:
      - nginx_volume:/usr/share/nginx/html

volumes:
  nginx_volume:
