services:
  web:
    build:
      context: ..
      dockerfile: release/prod.Dockerfile
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`bishojo.gsk-tsukuba.net`)
      traefik.http.routers.web.entrypoints: websecure,web
      traefik.http.routers.web.tls.certresolver: lehttp
      traefik.docker.network: "traefik-network"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
