services:
  web:
    build:
      context: ..
      dockerfile: release/prod.Dockerfile
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`bishojo.gsk-tsukuba.net`)
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.tls.certresolver: lehttp

networks:
  traefik-network:
    external: true
