name: CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: homepage

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Create PAT Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.ACTIONS_BOT_APP_ID }}
          private-key: ${{ secrets.ACTIONS_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "homepage,homepage-fonts"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
      - name: Get Current Time (Tag Name)
        id: tag
        run: echo "time=$(date +%Y%m%d%H%M%S%9N)" >> $GITHUB_OUTPUT
      - name: Basic Auth
        run: echo '${{ secrets.BASIC_PASSWD }}' | htpasswd -i -c ./nginx/.htpasswd ${{ secrets.BASIC_USER }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: beta/Dockerfile
          tags: ${{ env.REGISTRY }}/tsukuba-gsk-bishoge/${{ env.IMAGE_NAME }}:latest
          buildArgs: |
            BASIC_USER=${{ secrets.BASIC_USER }}
            BASIC_PASSWD=${{ secrets.BASIC_PASSWD }}
      - name: Update compose timestamp
        run: sed -i '1 s/#timestamp/#timestamp:${{ steps.tag.outputs.time }}/g' beta/docker-compose.yml
      - name: Push docker-compose.yml to release branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: beta
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
