name: CI

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Node Packages Installation
        run: npm install
      - name: ESLint
        run: npm run eslint:check
      - name: Prettier
        run: npm run format:check
