name: deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: homepage

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Get Current Time (Tag Name)
      #   id: tag
      #   run: echo "time=$(date +%Y%m%d%H%M%S%9N)" >> $GITHUB_OUTPUT
      - name: Show current dir
        run: ls -la
      - name: Basic Auth
        run: echo '${{ secrets.BASIC_PASSWD }}' | htpasswd -i -c ./nginx/.htpasswd ${{ secrets.BASIC_USER }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}"
          file: release/prod.Dockerfile
          tags: ${{ env.REGISTRY }}/tsukuba-gsk-bishoge/${{ env.IMAGE_NAME }}:latest

          # tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.time }}

      # - name: Convert base_url for gh-pages
      #   run: sed -i '3 s/ghcr.io\/tsukuba-GSK-bishoge\/homepage\/website/ghcr.io\/tsukuba-GSK-bishoge\/homepage\/website:${{ steps.tag.outputs.time }}/g' compose.yml
      # - name: Show release/prod.compose.yml
      #   run: cat release/prod.compose.yml
      # - name: Push prod.compose.yml to release branch
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: release
      #     FOLDER: release
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
